-- ============================================
-- UniGPT Premium Database Schema (v2)
-- Optimized for Hybrid Stack: Supabase + Pinecone
-- ============================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─── ENUM Types ───
-- Dropping types if they exist to recreate (only if running first time or clean start)
-- DO NOT drop if already in production. But since we are "migrating", we assume development sync.
DROP TYPE IF EXISTS doc_type_enum CASCADE;
DROP TYPE IF EXISTS user_role_enum CASCADE;

CREATE TYPE doc_type_enum AS ENUM ('student', 'faculty', 'admin', 'public');
CREATE TYPE user_role_enum AS ENUM ('student', 'faculty', 'admin');

-- ─── Profiles Table (Unified Auth) ───
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL DEFAULT '',
    role user_role_enum NOT NULL DEFAULT 'student',
    avatar_url TEXT,
    department TEXT,
    bio TEXT,
    preferences JSONB DEFAULT '{"theme": "system", "language": "en"}'::jsonb,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexing for speed
CREATE INDEX idx_profiles_email ON public.profiles(email);
CREATE INDEX idx_profiles_role ON public.profiles(role);

-- ─── Documents Table (Metadata) ───
CREATE TABLE IF NOT EXISTS public.documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    uploader_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    doc_type doc_type_enum NOT NULL DEFAULT 'public',
    department TEXT,
    course TEXT,
    tags TEXT[] DEFAULT '{}',
    file_size BIGINT, -- in bytes
    mime_type TEXT,
    page_count INTEGER,
    summary TEXT, -- LLM generated summary
    visibility BOOLEAN NOT NULL DEFAULT true,
    metadata JSONB DEFAULT '{}'::jsonb,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_documents_doc_type ON public.documents(doc_type);
CREATE INDEX idx_documents_uploader ON public.documents(uploader_id);
CREATE INDEX idx_documents_department ON public.documents(department);
CREATE INDEX idx_documents_course ON public.documents(course);

-- ─── Conversations (Chat History) ───
CREATE TABLE IF NOT EXISTS public.conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role user_role_enum NOT NULL,
    title TEXT DEFAULT 'New Conversation',
    messages JSONB DEFAULT '[]'::jsonb,
    summary TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    last_active TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_conversations_user ON public.conversations(user_id);
CREATE INDEX idx_conversations_last_active ON public.conversations(last_active DESC);

-- ─── Audit Logs (Security & Compliance) ───
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    payload JSONB DEFAULT '{}'::jsonb,
    ip_address TEXT,
    status TEXT DEFAULT 'success', -- 'success', 'failure', 'warning'
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_logs_user ON public.audit_logs(user_id);
CREATE INDEX idx_audit_logs_action ON public.audit_logs(action);
CREATE INDEX idx_audit_logs_timestamp ON public.audit_logs(timestamp DESC);

-- ─── RAG Evaluations (W&B style experiment/quality tracking) ───
CREATE TABLE IF NOT EXISTS public.rag_evaluations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    conversation_id UUID REFERENCES public.conversations(id) ON DELETE CASCADE,
    query TEXT NOT NULL,
    answer TEXT NOT NULL,
    context_used JSONB DEFAULT '[]'::jsonb, -- Store retrieved chunks information
    relevance_score FLOAT, -- How relevant the retrieval was (0-1)
    faithfulness_score FLOAT, -- How faithful the answer was to the context
    latency_ms INTEGER,
    token_usage JSONB DEFAULT '{}'::jsonb, -- {prompt, completion, total}
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_rag_eval_conv ON public.rag_evaluations(conversation_id);

-- ─── Row Level Security (RLS) ───
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rag_evaluations ENABLE ROW LEVEL SECURITY;

-- ─── Policies ───

-- Profiles: Own read/write
CREATE POLICY profiles_self_access ON public.profiles
    FOR ALL USING (auth.uid() = id);

-- Documents: Role based filtering
CREATE POLICY documents_access ON public.documents
    FOR SELECT USING (
        visibility = true AND (
            doc_type = 'public' 
            OR doc_type::text = (SELECT role::text FROM public.profiles WHERE id = auth.uid())
            OR EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
        )
    );

CREATE POLICY documents_modify_faculty_admin ON public.documents
    FOR ALL USING (
        EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('admin', 'faculty'))
    );

-- Conversations: Only own
CREATE POLICY conversations_self_access ON public.conversations
    FOR ALL USING (auth.uid() = user_id);

-- Audit Logs & RAG Eval: Admin only
CREATE POLICY admin_only_audit_eval ON public.audit_logs
    FOR SELECT USING (
        EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
    );

CREATE POLICY admin_only_rag_eval ON public.rag_evaluations
    FOR ALL USING (
        EXISTS(SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
    );

-- ─── Triggers for updated_at ───
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_profiles_modtime BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_documents_modtime BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_conversations_modtime BEFORE UPDATE ON public.conversations FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
